language: python

python:
  - 2.7
script:
  - python helloworld.py
  
deploy:
  provider: pages
  skip-cleanup: true
  #github-token: 9e4a5417b0e1600cb90696ef926df5c9aafb11a2
  #travis encrypt build=travisci --add env.matrix
  user: "sureshpuram"
  password: "travis123"
  keep-history: true
  on:
    branch: master
    local-dir: ./index.html
