language: python

python:
  - 2.7
script:
  - python helloworld.py
  
deploy:
  provider: pages
  skip-cleanup: true
  github-token: dca6ce72d59a905a954534b5950ab72b7f30f205
  keep-history: true
  on:
    branch: master
