language: python

python:
  - 2.7
script:
  - python helloworld.py
  
deploy:
  provider: pages
  skip-cleanup: true
  github-token: 77f3153aa9d8208070e30c2ae2faabdb2a7a741f
  #travis encrypt build=travisci --add env.matrix
  keep-history: true
  on:
    branch: master
    local-dir: ./index.html
