language: python

python:
  - 2.7
script:
  - python helloworld.py
  
deploy:
  provider: pages
  skip-cleanup: true
  github-token: 5e1cb30012dc126a288ed6c508f084a1a90d7e38
  keep-history: true
  on:
    branch: master
