language: python

python:
  - 2.7
script:
  - python helloworld.py
  
deploy:
  provider: pages
  skip-cleanup: true
  github-token: 2c9262c42050ec2ea4ed83e50502864e927e6cca
  user: "sureshpuram"
  password: "travis123"
  keep-history: true
  on:
    branch: master
