language: python

python:
  - 2.7
script:
  - python helloworld.py
  
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $build
  #travis encrypt build=travisci --add env.matrix
  keep-history: true
  on:
    branch: master
    
