language: python

python:
  - 2.7
script:
  - python helloworld.py
  
deploy:
  provider: pages
  skip-cleanup: true
  github-token: eIlyFhQWuPwK3-Vbr_yYfg # $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master
